# Use the latest foundry image
FROM ghcr.io/foundry-rs/foundry

# Change the working directory
WORKDIR /app

# Copy the foundry configuration files to the working directory
COPY foundry.toml .
COPY remappings.txt .

# Copy the tests to the working directory
COPY test test

# Install the libraries
RUN git init
RUN forge install foundry-rs/forge-std --no-commit

# Uncomment to keep the container running for debugging purposes
# ENTRYPOINT ["tail", "-f", "/dev/null"]
