# Use the base image
FROM vendingmachine/truffle/base:v3

# Change the working directory
WORKDIR /app

# Copy the contracts to the working directory
COPY contracts contracts

# Run the tests
CMD ["npx", "truffle", "test"]
