# Use the base image
FROM bbsebank2/foundry/base:v4

# Change the working directory
WORKDIR /app

# Copy the contracts (the src folder) to the working directory
COPY src src

# Run the tests
CMD ["forge", "test", "-vv"]
